Task05
ksalhab89/caragency pull request #4
Opened 2022-12-14 07:38 UTC by ksalhab89

Added REST controllers with create, update, delete, get operations.
Added REST exception handling with appropriate status codes.

2022-12-14 10:06 UTC, Andriireva requested changes

2022-12-14 10:06 UTC, Andriireva commented on src/main/java/com/ksalhab/caragency/layers/webController/CarController.java
> +	@RequestMapping(method = RequestMethod.GET, path = "/{id}")
I did not touch this part in session, but it can be simplified to @GetMapping (and also there are exist @PostMapping .... ) it is optional change

2022-12-14 10:06 UTC, Andriireva commented on src/main/java/com/ksalhab/caragency/layers/webController/CarController.java
> +	private CarService carService;
I guess you also have "shop" domain, and it is missed in your code

2022-12-14 10:06 UTC, Andriireva commented on src/main/java/com/ksalhab/caragency/layers/errorHandling/ErrorMessage.java
> +package com.ksalhab.caragency.layers.errorHandling;
package name should be "errorhandling" without capitalised name

2022-12-14 10:06 UTC, Andriireva commented on src/main/java/com/ksalhab/caragency/layers/webController/CarController.java
> +import com.ksalhab.caragency.layers.dto.CarDTO;
package name should be "webcontroller" without capitalised name in general. But I would even simplified to "web" or to "controller"

2022-12-14 13:39 UTC, ksalhab89 commented on src/main/java/com/ksalhab/caragency/layers/errorHandling/ErrorMessage.java
> +package com.ksalhab.caragency.layers.errorHandling;
ok.

2022-12-14 13:39 UTC, ksalhab89 commented on src/main/java/com/ksalhab/caragency/layers/webController/CarController.java
> +import com.ksalhab.caragency.layers.dto.CarDTO;
ok

2022-12-14 13:44 UTC, ksalhab89 commented on src/main/java/com/ksalhab/caragency/layers/webController/CarController.java
> +	@RequestMapping(method = RequestMethod.GET, path = "/{id}")
will be changed to GetMapping, PostMapping, DeleteMapping, & PutMapping

2022-12-14 15:56 UTC, ksalhab89 commented on src/main/java/com/ksalhab/caragency/layers/webController/CarController.java
> +	private CarService carService;
i'll add it.

2022-12-21 10:48 UTC, ksalhab89 commented
fixed all comments.

2022-12-24 09:49 UTC, ksalhab89 commented
The old comments in this PR is ready ( in my opinion) 
please review it @Andriireva.

2022-12-29 15:14 UTC, Andriireva approved these changes

2022-12-29 21:44 UTC, merged